---
collections:
  # - redhat.satellite
  # - redhat.insights
  # - ansible.tower
  # - amazon.aws
  # - redhat_cop.tower_configuration
  - community.general
  #https://github.com/theforeman/foreman-ansible-modules
