- name: Download-ssg
  hosts: RHEL7_Dev
  become: true
  tasks:
    - name: Refresh Red Hat subscription
      ansible.builtin.command: subscription-manager refresh
      register: refresh_output
      changed_when: false

    - name: Clean all yum metadata
      ansible.builtin.command: yum clean all
      register: clean_output
      changed_when: false

    - name: List enabled repositories
      ansible.builtin.command: yum repolist
      register: repolist_output
      changed_when: false

    - name: Search for scap-security-guide package
      ansible.builtin.command: yum search scap-security-guide
      register: scap_search
      changed_when: false

    - name: Show result of scap package search
      ansible.builtin.debug:
        msg: "{{ scap_search.stdout_lines }}"