- name: Download-ssg
  hosts: RHEL7_Dev
  become: true
  vars:
      rhsm_username: amysoh
      rhsm_password: Kopimickey141220!

  tasks:
    - name: Check if system is already registered
      ansible.builtin.command: subscription-manager status
      register: subscription_status
      failed_when: false
      changed_when: false

    - name: Register system to Red Hat if not already registered
      ansible.builtin.command: >
        subscription-manager register
        --username={{ rhsm_username }}
        --password={{ rhsm_password }}
      when: "'Overall Status: Unknown' in subscription_status.stdout"
      register: register_output
      changed_when: "'The system has been registered' in register_output.stdout"

    - name: Auto-attach subscription
      ansible.builtin.command: subscription-manager attach --auto
      when: "'Overall Status: Unknown' in subscription_status.stdout"
      register: attach_output
      changed_when: "'Successfully attached a subscription' in attach_output.stdout"