- name: Download-ssg
  hosts: RHEL7_Dev
  become: true
  tasks:
    - name: Check subscription status
      ansible.builtin.command: subscription-manager status
      register: sub_status
      changed_when: false

    - name: Enable required Red Hat repos
      ansible.builtin.command: >
        subscription-manager repos
        --enable=rhel-7-server-rpms
        --enable=rhel-7-server-extras-rpms
        --enable=rhel-7-server-optional-rpms
      register: enable_repos
      changed_when: "'enabled' in enable_repos.stdout"

    - name: Install scap-security-guide package
      ansible.builtin.yum:
        name: scap-security-guide
        state: present
