- name: Download-ssg
  hosts: RHEL7_Dev
  become: true
  tasks:
    - name: Enable required RHEL 7 repositories
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl | default(omit) }}"
        enabled: yes
      loop:
        - { name: rhel-7-server-rpms, description: RHEL 7 Server RPMs }
        - { name: rhel-7-server-extras-rpms, description: RHEL 7 Server Extras RPMs }
        - { name: rhel-7-server-optional-rpms, description: RHEL 7 Server Optional RPMs }

    - name: Install scap-security-guide package
      ansible.builtin.yum:
        name: scap-security-guide
        state: present

    - name: Verify SCAP content directory
      ansible.builtin.stat:
        path: /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
      register: scap_file

    - name: Debug SCAP content presence
      ansible.builtin.debug:
        msg: "SCAP content found: {{ scap_file.stat.exists }}"