- name: Download-ssg
  hosts: RHEL7_Dev
  become: true
  vars:
    rex_pub_key_path: files/satellite.pub

  tasks:
    - name: Ensure /root/.ssh directory exists
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Copy Satellite Remote Execution public key
      ansible.builtin.copy:
        src: "{{ rex_pub_key_path }}"
        dest: /root/.ssh/authorized_keys
        mode: '0600'
        owner: root
        group: root
        backup: yes

    - name: Ensure public key is present and not duplicated
      ansible.builtin.lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ lookup('file', rex_pub_key_path) }}"
        create: yes
        state: present