- name: Download-ssg
  hosts: RHEL7_Dev
  become: true
  tasks:
    - name: Install scap-security-guide package
      ansible.builtin.yum:
        name: scap-security-guide
        state: present

    - name: Verify SCAP content directory
      ansible.builtin.stat:
        path: /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
      register: scap_file

    - name: Debug SCAP content presence
      ansible.builtin.debug:
        msg: "SCAP content found: {{ scap_file.stat.exists }}"